### ISSUE TITLE
coult not find or load main class metabase.core

### ISSUE THREAD

**Issue by sirawichj** [hellonico/metabase-csv-sample#2]
as I am a newbie for coding, I downloaded csvjdbc.jar and metabase.jar and tried to run the code java -cp csvjdbc.jar:metabase.jar metabase.core in command line but I got error "coult not find or load main class metabase.core"

please help thank you 

![1580483966509](https://user-images.githubusercontent.com/2182680/73550803-d85d1f80-4477-11ea-9530-9db7661375c3.jpg)
![1580483990064](https://user-images.githubusercontent.com/2182680/73550806-da26e300-4477-11ea-80cf-8618d8a21173.jpg)

**Comment by hellonico** [comment]
Just make sure you rename the jar file according to the script.
See the content of the project once the jar files have been renamed.

```
SuperPinkicious:metabase-csv-sample niko$ tree
.
├── BURGERS
│   ├── BigMac.201107.csv
│   ├── BigMac.201201.csv
│   ├── BigMac.201207.csv
│   ├── BigMac.201301.csv
│   ├── BigMac.201307.csv
│   ├── BigMac.201401.csv
│   ├── BigMac.201407.csv
│   ├── BigMac.201501.csv
│   ├── BigMac.201507.csv
│   ├── BigMac.201601.csv
│   ├── BigMac.201607.csv
│   ├── BigMac.201701.csv
│   ├── BigMac.201707.csv
│   └── BigMac.201801.csv
├── README.md
├── burgers.png
├── csvjdbc.jar
├── metabase.db.mv.db
├── metabase.db.trace.db
├── metabase.jar
├── start.bat
└── start.sh

1 directory, 22 files
```
